server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /projects {
        proxy_pass http://scanner:8000;
    }

    location /scans {
        proxy_pass http://scanner:8000;
    }

    location /health {
        proxy_pass http://scanner:8000;
    }
}
