services:
  scanner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/scanner.db
      - DEMO_API_URL=http://demo_api:8000
    volumes:
      - .:/app
      - scanner_data:/app/data
      - ./sample_reports:/app/sample_reports
    depends_on:
      - demo_api
      - vampi
    networks:
      - scanner-net

  vampi:
    image: erev0s/vampi:latest
    container_name: vampi
    ports:
      - "9001:5000"
    environment:
      - ENV_file=False
    networks:
      - scanner-net

  demo_api:
    build:
      context: ./demo_api
      dockerfile: Dockerfile
    ports:
      - "9002:8000"
    environment:
      - DEMO_API_SECRET_KEY=demosecret # Default research key; CHANGE FOR PRODUCTION
    networks:
      - scanner-net

networks:
  scanner-net:


volumes:
  scanner_data:
